export const FILMS = [
  {
    id: "film-01",
    title: "Saudi Joker",
    duration: "--:--",
    year: "2026",
    description: "فيلم سينمائي قصير بعالم بصري سعودي جريء.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/50408478a_poster_01_saudi_joker.jpg",
  },
  {
    id: "film-02",
    title: "Human Snail",
    duration: "--:--",
    year: "2026",
    description: "مشهد مستقبلي عن الإنسان والتحوّل داخل مدينة صامتة.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/299cf4ec4_poster_02_human_snail.jpg",
  },
  {
    id: "film-03",
    title: "Mohammed Writer",
    duration: "--:--",
    year: "2026",
    description: "بورتريه سينمائي لكاتب يعيش بين الواقع وخياله الداخلي.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/896efbb93_poster_03_mohammed_writer.jpg",
  },
  {
    id: "film-04",
    title: "Studies Fragments",
    duration: "--:--",
    year: "2026",
    description: "شظايا دراسة بصرية داخل عالم فني ملوّن ومضطرب.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/b16bc79a7_poster_04_studies_fragments.jpg",
  },
  {
    id: "film-05",
    title: "Disorders",
    duration: "--:--",
    year: "2026",
    description: "تجربة بصرية عن التشوش، الذاكرة، والانفصال عن الجسد.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/2d82fa3a9_poster_05_disorders.jpg",
  },
  {
    id: "film-06",
    title: "Saudi Harley",
    duration: "--:--",
    year: "2026",
    description: "طاقة سعودية معاصرة بإيقاع شارع وحضور قوي.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/0950d3939_poster_06_saudi_harley.jpg",
  },
  {
    id: "film-07",
    title: "Glasses Cinematic",
    duration: "--:--",
    year: "2026",
    description: "إعلان سينمائي لنظارة بحضور راقٍ وحركة مدروسة.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/9a663b1cb_poster_07_glasses_cinematic.jpg",
  },
  {
    id: "film-08",
    title: "Glasses UGC",
    duration: "--:--",
    year: "2026",
    description: "محتوى قريب من الجمهور لنظارة ذكية بأسلوب يومي مباشر.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/e1ce15d4d_poster_08_glasses_ugc.jpg",
  },
  {
    id: "film-09",
    title: "Generations",
    duration: "--:--",
    year: "2026",
    description: "حكاية أجيال وصورة ذاكرة تتقاطع مع المستقبل.",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    thumbnail: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/37ab695a0_poster_09_generations.jpg",
  },
];