import { realEstateItems } from "./realEstateItems";

// Main vertical feed — one section per category
export const CATEGORIES = [
  {
    id: "ai-fashion",
    slug: "/ai-fashion",
    title: "الأزياء والافتتاحيات",
    titleEn: "Fashion Editorials",
    subtitle: "افتتاحيات أزياء، حملات ستوديو، ستريت وير، مجوهرات، وهوية بصرية للعلامات",
    subtitleEn: "Fashion editorials, studio campaigns, streetwear, jewelry, and brand visual identity",
    seoDescription: "Turki Ghazi fashion portfolio — cinematic fashion editorials, AI-assisted campaign art direction, luxury styling, streetwear visuals, jewelry stories, and Saudi fashion identity.",
    introText: "عالم أزياء محرّر بعين سينمائية ومزاج حملات عالمية",
    introTextEn: "A fashion world curated with cinematic direction and global campaign energy",
    coverImage: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/160b401e0_fashion.jpg",
    color: "from-rose-950/80",
    items: [
      {
        id: "af-red-power",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/258bc65f6_f_159.jpg",
        alt: "Red power suit fashion editorial portrait with luxury styling",
        title: "RED POWER",
        description: "افتتاحية أزياء حادة باللون الأحمر، مناسبة لحملات القوة، الثقة، والحضور النسائي الفاخر.",
        descriptionEn: "A sharp red fashion editorial built for power, confidence, and premium feminine presence.",
      },
      {
        id: "af-vogue-family",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/8ad1aa98c_f_146.jpg",
        alt: "Vogue inspired neutral fashion group editorial campaign",
        title: "EARTH EDITORIAL",
        description: "حملة جماعية بدرجات ترابية راقية تمنح العلامة إحساس المجلات العالمية والهدوء الفاخر.",
        descriptionEn: "A refined earth-toned group editorial with international magazine energy and quiet luxury.",
      },
      {
        id: "af-couture-blue",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/d89281c03_f_128.jpg",
        alt: "Couture fashion editorial with vivid blue architecture and pink gowns",
        title: "BLUE COUTURE",
        description: "تكوين معماري جريء يضع الفساتين كمنحوتات لونية داخل مساحة زرقاء عالية التذكّر.",
        descriptionEn: "A bold architectural couture story where dresses become color sculptures in a blue world.",
      },
      {
        id: "af-jewelry-ruby",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/05d6879cd_f_143.jpg",
        alt: "Luxury ruby jewelry beauty editorial closeup",
        title: "RUBY JEWELS",
        description: "قصة مجوهرات فاخرة تركّز على البشرة، اللمعة، والحجر الأحمر كبطل بصري للحملة.",
        descriptionEn: "A luxury jewelry story focused on skin, sparkle, and ruby stones as the campaign hero.",
      },
      {
        id: "af-black-chain",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/d18cdb4f3_f_121.jpg",
        alt: "Black leather fashion editorial with giant metallic chains",
        title: "CHAIN FORM",
        description: "افتتاحية جلد أسود بطابع مستقبلي، تستخدم السلاسل كعنصر قوة وحركة داخل الإطار.",
        descriptionEn: "A futuristic black leather editorial using oversized chains as power and movement cues.",
      },
      {
        id: "af-denim-desert",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/3b4f0a5ec_f_157.jpg",
        alt: "Surreal denim jacket fashion campaign in the desert",
        title: "DENIM MIRAGE",
        description: "فكرة أزياء سريالية تربط الدنيم بالصحراء، وتحوّل القطعة إلى عالم بصري قابل للتسويق.",
        descriptionEn: "A surreal denim campaign connecting fabric, scale, and desert into a marketable visual world.",
      },
      {
        id: "af-urban-leather",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/7b9f4eb45_f_155.jpg",
        alt: "Urban fashion low angle leather and denim editorial between skyscrapers",
        title: "CITY ARMOR",
        description: "ستريت وير حضري بإحساس قوي وعدسة منخفضة تعطي الملابس حضورًا أكبر من الواقع.",
        descriptionEn: "Urban streetwear with a strong low-angle lens that gives the look larger-than-life presence.",
      },
      {
        id: "af-red-studio",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/173739969_f_130.jpg",
        alt: "Red studio denim fashion editorial with motion blur",
        title: "RED DENIM",
        description: "حملة دنيم شبابية بإضاءة حمراء وحركة خفيفة تصنع إحساس الموسيقى والسرعة.",
        descriptionEn: "A youth denim campaign with red lighting and motion blur for music-driven energy.",
      },
      {
        id: "af-design-studies",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/b51f756a5_f_080.jpg",
        alt: "Fashion design study board with cargo pants sketches and fabric swatches",
        title: "DESIGN STUDIES",
        description: "توظيف ذكي لمرحلة ما قبل الإنتاج: باترونات، خامات، وملاحظات تصميم تُظهر عمق العملية الإبداعية.",
        descriptionEn: "A smart pre-production visual: patterns, fabrics, and design notes showing creative depth.",
      },
      {
        id: "af-flower-bomber",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/7b1320603_f_120.jpg",
        alt: "Conceptual floral bomber jacket fashion campaign in a meadow",
        title: "BLOOM JACKET",
        description: "حملة شاعرية لقطعة جاكيت، تجعل الأزهار جزءًا من بناء المنتج لا مجرد خلفية.",
        descriptionEn: "A poetic jacket campaign where flowers become part of the product story, not just decoration.",
      },
      {
        id: "af-snail-pop",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/55e3d0442_f_135.jpg",
        alt: "Pastel fashion campaign with oversized surreal snail sculpture",
        title: "PASTEL CREATURE",
        description: "عالم أزياء مرح وسريالي مناسب للعلامات الشبابية التي تبحث عن صورة مختلفة ولا تُنسى.",
        descriptionEn: "A playful surreal fashion world for youth brands seeking a different, unforgettable image.",
      },
      {
        id: "af-cloud-pink",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/2ce310de1_f_113.jpg",
        alt: "Pink loungewear fashion campaign model sitting on cloud",
        title: "CLOUDWEAR",
        description: "حملة مريحة وحالمة للملابس اليومية، تربط الراحة بالخيال والنعومة البصرية.",
        descriptionEn: "A soft dreamy loungewear campaign connecting comfort with imagination and visual softness.",
      },
      {
        id: "af-monochrome-thobe",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/7ca820dd7_f_134.jpg",
        alt: "Black and white Saudi menswear editorial seated on stairs",
        title: "SAUDI MINIMAL",
        description: "رجالي سعودي بأسلوب مينيمال أبيض وأسود، يعطي الثوب حضورًا معاصرًا وهادئًا.",
        descriptionEn: "A black-and-white Saudi menswear editorial giving traditional dress a calm modern presence.",
      },
      {
        id: "af-heritage-luxury",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/49da3edcf_f_158.jpg",
        alt: "Luxury Gulf fashion portrait in embroidered black abaya styling",
        title: "GULF LUXURY",
        description: "إطلالة خليجية فاخرة تجمع التطريز والعباءة السوداء مع لغة ستوديو عالمية.",
        descriptionEn: "A luxury Gulf look merging embroidery, black abaya styling, and global studio language.",
      },
      {
        id: "af-mint-future",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/f87439d47_f_151.jpg",
        alt: "Mint futuristic modest fashion campaign in white desert set",
        title: "MINT FUTURE",
        description: "أزياء محتشمة مستقبلية بدرجات منعشة، مناسبة لحملات الصيف والهوية النظيفة.",
        descriptionEn: "Futuristic modest fashion in fresh mint tones for summer and clean brand identity campaigns.",
      },
      {
        id: "af-studio-streetwear",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/3e777a074_f_101.jpg",
        alt: "Studio streetwear fashion campaign with colorful lighting setup",
        title: "STUDIO STREET",
        description: "ستريت وير داخل ستوديو واضح العناصر، يعرض الإضاءة كجزء من هوية الحملة لا كخلفية فقط.",
        descriptionEn: "Studio streetwear where lighting equipment becomes part of the campaign identity.",
      },
      {
        id: "af-burgundy-portrait",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/8d61f9dd6_f_148.jpg",
        alt: "Male fashion portrait with burgundy turtleneck and gold chain",
        title: "BURGUNDY PORTRAIT",
        description: "بورتريه أزياء رجالي كلاسيكي يركز على الخامة، اللون، وتعابير الوجه كهوية بصرية.",
        descriptionEn: "A classic menswear portrait focused on texture, color, and expression as visual identity.",
      },
      {
        id: "af-black-fur",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/092a4d8c30_f_116.jpg",
        alt: "Luxury dark fashion portrait with gray faux fur and purple neon glow",
        title: "NEON FUR",
        description: "فخامة ليلية بفراء رمادي وإضاءة بنفسجية، مناسبة لحملات الشتاء والموضة الجريئة.",
        descriptionEn: "Night luxury with gray fur and purple glow, ideal for winter and bold fashion campaigns.",
      }
    ],
  },
  {
    id: "commercial-ads",
    slug: "/commercial-ads",
    title: "الإعلانات التجارية",
    titleEn: "Commercial Ads",
    subtitle: "حملات إعلانية للمنتجات، المطاعم، العطور، الأزياء، والهوية التجارية",
    subtitleEn: "Commercial campaigns for products, F&B, fragrance, fashion, and brand identity",
    seoDescription: "Turki Ghazi commercial advertising portfolio — cinematic AI-powered product campaigns, food advertising, fragrance visuals, fashion products, and branded content for Saudi and Gulf brands.",
    introText: "إعلانات تجارية مصممة كعوالم بصرية لكل علامة",
    introTextEn: "Commercial ads designed as visual worlds for every brand",
    coverImage: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/ac5c3b2b1_ads.jpg",
    color: "from-amber-950/80",
    items: [
      {
        id: "ca-watch-party",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/e0f3957ef_a_071.jpg",
        alt: "Cinematic football watch party food and beverage campaign",
        title: "WATCH PARTY",
        description: "حملة مطاعم ومشروبات بإحساس اجتماعي سريع، مبنية حول لحظة المشاهدة والحماس الجماعي.",
        descriptionEn: "A social F&B campaign built around match-day energy, reactions, and shared appetite.",
      },
      {
        id: "ca-match-night",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/d774bea96_a_068.jpg",
        alt: "Night football food commercial with cinematic Saudi living room energy",
        title: "MATCH NIGHT",
        description: "مشهد إعلاني ليلي عالي الإحساس يربط المنتج بالترقب، الضحك، واللحظة العائلية.",
        descriptionEn: "A night commercial scene connecting the product with anticipation, laughter, and family moments.",
      },
      {
        id: "ca-alwalimah",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/05ef27856_a_067.jpg",
        alt: "Saudi rice product campaign portrait with Alwalimah bag",
        title: "ALWALIMAH RICE",
        description: "حملة منتج غذائي بهوية سعودية واضحة، توازن بين الثقة الشعبية والحضور الإعلاني النظيف.",
        descriptionEn: "A Saudi food product campaign balancing familiar trust with clean commercial presence.",
      },
      {
        id: "ca-feast-table",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/0f426bf84_a_064.jpg",
        alt: "Hero food platter commercial for rice and feast campaign",
        title: "FEAST HERO",
        description: "لقطة طعام بطولية تضع المنتج في مركز الشهية، مناسبة للحملات الرمضانية والموسمية.",
        descriptionEn: "A heroic food visual placing the product at the center of appetite and seasonal campaigns.",
      },
      {
        id: "ca-laverne",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/35a5c91c4_a_061.jpg",
        alt: "Luxury fragrance product advertising visual with cinematic lighting",
        title: "FRAGRANCE WORLD",
        description: "عالم عطري فاخر يعتمد على الضوء، الزجاج، واللون لصناعة إحساس راقٍ حول المنتج.",
        descriptionEn: "A luxury fragrance world using light, glass, and color to build premium product desire.",
      },
      {
        id: "ca-natural-life",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/a065584b3_a_059.jpg",
        alt: "Lifestyle cafe brand campaign for Natural Life",
        title: "NATURAL LIFE",
        description: "حملة لايف ستايل تربط المكان بالشخصية، وتحوّل الزيارة اليومية إلى صورة قابلة للتسويق.",
        descriptionEn: "A lifestyle campaign connecting place and personality, turning daily visits into marketable visuals.",
      },
      {
        id: "ca-leather-goods",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/80f907059_a_041.jpg",
        alt: "Luxury leather bag product photography with warm premium styling",
        title: "LEATHER GOODS",
        description: "تصوير منتج فاخر يبرز الخامة والملمس والتفاصيل الصغيرة كقيمة أساسية للعلامة.",
        descriptionEn: "Premium product photography highlighting texture, material, and detail as brand value.",
      },
      {
        id: "ca-skincare",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/8c5f55313_a_026.jpg",
        alt: "Warm skincare product campaign with monochrome yellow art direction",
        title: "SKINCARE SET",
        description: "توجيه فني لمنتجات العناية بأسلوب لوني موحد يمنح الحملة وضوحًا وتذكّرًا سريعًا.",
        descriptionEn: "A skincare campaign with unified color direction for clarity, recall, and shelf appeal.",
      },
      {
        id: "ca-burger-concept",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/445e110e0_a_010.jpg",
        alt: "Bold cinematic burger advertising concept with red restaurant lighting",
        title: "BOLD BURGER",
        description: "إعلان طعام جريء بطابع شبابي، يستخدم المبالغة البصرية لصناعة لقطة لا تُنسى.",
        descriptionEn: "A bold youth-driven food ad using visual exaggeration to create a memorable frame.",
      },
      {
        id: "ca-cold-drinks",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/2cef9a0a1_a_009.jpg",
        alt: "Refreshing beverage product campaign inside a chilled fridge",
        title: "COLD SHELF",
        description: "حملة مشروبات تركز على الإحساس البارد، الرف التجاري، ولحظة الاختيار السريعة.",
        descriptionEn: "A beverage campaign focused on cold freshness, retail shelves, and instant product choice.",
      },
      {
        id: "ca-luxury-set",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/daf7c925d_a_002.jpg",
        alt: "Luxury branded merchandise flat lay with hoodie, candle, bottle, and stationery",
        title: "BRAND OBJECTS",
        description: "توظيف الهوية على منتجات ملموسة بأسلوب هادئ وفاخر يصلح للعلامات الراقية والمتاجر الخاصة.",
        descriptionEn: "A refined branded merchandise setup for premium labels, private stores, and identity systems.",
      },
    ],
  },
  {
    id: "trained-models",
    slug: "/trained-models",
    title: "الشخصيات المدرّبة",
    titleEn: "Trained Characters",
    subtitle: "شخصيات ثابتة الهوية، لكل شخصية ملف صور وزوايا مستقل",
    subtitleEn: "Persistent AI characters, each with a dedicated image and angle library",
    seoDescription: "Turki Ghazi trained AI characters portfolio — persistent character identities with separate galleries, facial angles, fashion, ads, films, and campaign-ready model references.",
    introText: "ادخل كتالوج الشخصيات واختر كل شخصية لاستعراض زواياها الخاصة",
    introTextEn: "Enter the character catalog and open each identity through its dedicated angles",
    coverImage: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/e127e9f93_angle_1.jpg",
    color: "from-stone-950/80",
    items: [],
  },
  {
    id: "films",
    slug: "/films",
    title: "الأفلام السينمائية",
    titleEn: "Films",
    subtitle: "تجربة مشاهدة مختارة بإيقاع سينمائي هادئ",
    subtitleEn: "A curated cinema experience with quiet visual rhythm",
    seoDescription: "Turki Ghazi cinematic films portfolio — short AI-powered films, visual stories, and behind-the-scenes cinema experiments.",
    introText: "أفلام قصيرة تُشاهد كتجربة سينمائية لا كمعرض صور",
    introTextEn: "Short films experienced as cinema, not image galleries",
    coverImage: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/115dd4f4c_films.jpg",
    color: "from-stone-950/80",
    items: [],
  },
  {
    id: "real-estate",
    slug: "/real-estate",
    title: "العقار والتطوير",
    titleEn: "Real Estate Development",
    subtitle: "واجهات فاخرة، تجارب سكنية، إطلاق مشاريع، وتسويق عقاري سينمائي",
    subtitleEn: "Luxury façades, lifestyle moments, project launches, and cinematic property marketing",
    seoDescription: "Turki Ghazi real estate portfolio — cinematic luxury property marketing, Riyadh residential developments, architectural façades, investor presentations, virtual tours, and premium real estate campaigns.",
    introText: "نحوّل المشروع العقاري إلى قصة بصرية تبيع الإحساس والقيمة معًا",
    introTextEn: "We turn real estate projects into visual stories that sell both feeling and value",
    coverImage: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/a88c46ce7_r_041.jpg",
    color: "from-emerald-950/80",
    items: realEstateItems,
  },
  {
    id: "heritage",
    slug: "/heritage",
    title: "التراث والذاكرة",
    titleEn: "Heritage Memory",
    subtitle: "حكايات نجد، شوارع الرياض القديمة، السيارات الكلاسيكية، والذاكرة اليومية بلغة سينمائية",
    subtitleEn: "Najdi stories, old Riyadh streets, classic cars, and everyday memory in cinematic language",
    seoDescription: "Turki Ghazi heritage visual portfolio — cinematic Saudi heritage storytelling, old Riyadh neighborhoods, Najdi architecture, classic cars, cultural memory, and Gulf identity visuals.",
    introText: "تراث لا يُعرض كأرشيف، بل كفيلم حي من الذاكرة السعودية",
    introTextEn: "Heritage presented not as archive, but as a living film of Saudi memory",
    coverImage: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/66f44173f_heritage.jpg",
    color: "from-amber-950/80",
    items: [
      {
        id: "he-bofiya",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/e227092f5_h_021.jpg",
        alt: "Old Saudi neighborhood bofia sign at golden hour",
        title: "BOFIYA MEMORY",
        description: "لقطة افتتاحية تحمل رائحة المكان: لوحة بوفية قديمة، ضوء آخر النهار، وباب مفتوح لذاكرة الحي.",
        descriptionEn: "An opening memory frame: an old bofia sign, late sun, and a doorway into neighborhood nostalgia.",
      },
      {
        id: "he-rooftops",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/f6fa7a949_h_020.jpg",
        alt: "Aerial view of old Riyadh neighborhood rooftops in warm light",
        title: "ROOFTOP CITY",
        description: "مشهد علوي يكشف نسيج الرياض القديم؛ أسطح متقاربة، خزانات ماء، وشوارع تحفظ إيقاع الحياة اليومية.",
        descriptionEn: "An aerial view of old Riyadh: close rooftops, water tanks, and streets holding daily rhythm.",
      },
      {
        id: "he-classic-cruise",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/c98ca1ba7_h_018.jpg",
        alt: "Classic Mercedes convertible cruising near mosque and flowers",
        title: "RIYADH CRUISE",
        description: "سيارة كلاسيكية تتحرك بهدوء بين النخيل والمسجد؛ فخامة قديمة بروح سعودية خفيفة.",
        descriptionEn: "A classic convertible gliding past palms and mosque silhouettes — old elegance with Saudi ease.",
      },
      {
        id: "he-night-drift",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/1b2827777_h_017.jpg",
        alt: "Red classic car drifting at night on wet city street",
        title: "NIGHT BURNOUT",
        description: "جانب حضري من الذاكرة: شارع مبتل، سيارة حمراء، ودخان يصنع لقطة إعلان سينمائية عالية الطاقة.",
        descriptionEn: "An urban memory frame: wet asphalt, a red car, and smoke shaping a high-energy cinematic ad shot.",
      },
      {
        id: "he-village-drive",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/ece892a19_h_016.jpg",
        alt: "Saudi man driving classic car through heritage village",
        title: "VILLAGE DRIVER",
        description: "سرد بصري من داخل السيارة؛ العائلة، الأطفال، بائع الآيسكريم، وشارع تراثي يتحرك حول الشخصية.",
        descriptionEn: "A story from inside the car: family, children, ice-cream truck, and a heritage street moving around the character.",
      },
      {
        id: "he-heritage-lane",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/bed675303_h_015.jpg",
        alt: "Classic convertible entering old Saudi village street at sunset",
        title: "DUST LANE",
        description: "زقاق تراثي ممتلئ بالغبار والضوء، يصنع إحساس العودة للمكان لا مجرد زيارته.",
        descriptionEn: "A dusty golden heritage lane that feels like returning to a place, not merely visiting it.",
      },
      {
        id: "he-palm-square",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/044cbe3ab_h_014.jpg",
        alt: "Heritage village square with palms children and ice cream truck",
        title: "PALM SQUARE",
        description: "ساحة شعبية دافئة تجمع النخيل، الأطفال، العربة القديمة، والسيارة كرمز للرحلة بين زمنين.",
        descriptionEn: "A warm village square with palms, children, an old truck, and the car as a bridge between eras.",
      },
      {
        id: "he-classic-close",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/422bc7753_h_013.jpg",
        alt: "Classic red convertible close shot in old Saudi village",
        title: "RED IMPERIAL",
        description: "لقطة قريبة تجعل السيارة بطلة تراثية؛ معدن أحمر، انعكاس شمس، وخلفية نجدية ناعمة.",
        descriptionEn: "A close heroic classic car frame: red metal, sun reflection, and a soft Najdi backdrop.",
      },
      {
        id: "he-majlis-oud",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/caea3c6ed_h_012.jpg",
        alt: "Old Saudi majlis with oud player tapes radio and vintage TV",
        title: "MAJLIS SOUND",
        description: "ذاكرة المجلس كصوت وصورة: عود، أشرطة، راديو، تلفزيون قديم، وتفاصيل تحكي زمنًا كاملًا.",
        descriptionEn: "Majlis memory as sound and image: oud, tapes, radio, old TV, and details that hold an era.",
      },
      {
        id: "he-parking-classic",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/21de165c2_h_011.jpg",
        alt: "Classic convertible in Riyadh Boulevard parking with suited man",
        title: "BOULEVARD CLASSIC",
        description: "مزج بين الرياض الحديثة والذاكرة الكلاسيكية؛ موقف حضري وسيارة قديمة وشخصية أنيقة.",
        descriptionEn: "Modern Riyadh meets classic memory: an urban parking frame, vintage car, and elegant character.",
      },
      {
        id: "he-dust-sedan",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/a03442e2f_h_010.jpg",
        alt: "Dusty old sedan parked in old Saudi alley at sunset",
        title: "DUST SEDAN",
        description: "سيارة عادية لكنها محمّلة بالمعنى؛ غبار، غروب، وشارع قديم يصنع صدق الوثائقيات.",
        descriptionEn: "An ordinary car carrying meaning: dust, sunset, and an old street with documentary honesty.",
      },
      {
        id: "he-stone-truck",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/d4e943688_h_009.jpg",
        alt: "Old pickup truck in narrow heritage stone alley with warm lamps",
        title: "STONE ALLEY",
        description: "زقاق حجري ومصابيح دافئة وشاحنة قديمة؛ لقطة تصلح لهوية مسلسل أو فيلم تراثي.",
        descriptionEn: "Stone alley, warm lamps, and an old pickup — a frame fit for a heritage film identity.",
      },
      {
        id: "he-no-dumping",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/80fce6e03_h_008.jpg",
        alt: "Arabic no dumping sign in desert waste area with cats",
        title: "PUBLIC MEMORY",
        description: "لقطة نقدية ذكية من الذاكرة اليومية؛ لوحة رسمية، بيئة مهملة، وحكاية مدينة خلف الصورة.",
        descriptionEn: "A smart critical daily-memory frame: official sign, neglected ground, and a city story behind it.",
      },
      {
        id: "he-road-contrast",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/39449f7e3_h_007.jpg",
        alt: "Saudi highway traffic contrast between old dusty cars and luxury vehicles",
        title: "ROAD CONTRAST",
        description: "مقارنة بصرية بين القديم والجديد على طريق واحد؛ طبقات اجتماعية وزمنية في لقطة واحدة.",
        descriptionEn: "Old and new on one road — social and temporal layers compressed into a single frame.",
      },
      {
        id: "he-city-dust",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/568ce3c4c_h_006.jpg",
        alt: "Dusty old Ford sedan driving through Riyadh traffic",
        title: "CITY DUST",
        description: "سيارة متعبة وسط مدينة متغيرة؛ صورة تلخص انتقال الرياض بين الغبار والزجاج.",
        descriptionEn: "A tired car in a changing city — Riyadh suspended between dust and glass.",
      },
      {
        id: "he-wall-words",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/a7c16ed64_h_005.jpg",
        alt: "Arabic wall graffiti poem on old cracked Saudi wall",
        title: "WALL WORDS",
        description: "الجدار كدفتر شعبي؛ كتابة عفوية على طين متشقق تمنح التراث صوتًا لا صورة فقط.",
        descriptionEn: "The wall as a folk notebook: spontaneous writing on cracked clay giving heritage a voice.",
      },
      {
        id: "he-laundry-roofs",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/c95711343_h_004.jpg",
        alt: "Old neighborhood rooftops laundry lines and mosque minarets",
        title: "LAUNDRY ROOFS",
        description: "تفاصيل حياة لا تُفتعل: غسيل فوق الأسطح، مكيفات قديمة، ومآذن بعيدة داخل ضوء ذهبي.",
        descriptionEn: "Unstaged life details: rooftop laundry, old AC units, distant minarets, and golden light.",
      },
      {
        id: "he-old-street",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/0a2ead0e0_h_003.jpg",
        alt: "Old Saudi street with dusty beige car at sunset",
        title: "QUIET STREET",
        description: "هدوء شارع قديم قبل الليل؛ سيارة ساكنة وشمس منخفضة تمنح الصورة حنينًا صادقًا.",
        descriptionEn: "The quiet of an old street before night: a still car and low sun creating honest nostalgia.",
      },
      {
        id: "he-old-roofs",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/5774086f3_h_002.jpg",
        alt: "Compressed old Saudi rooftops and narrow alley view",
        title: "NARROW MEMORY",
        description: "منظر مضغوط بين الأسطح والممرات، يوثق الكثافة البصرية للحي القديم دون تجميل زائد.",
        descriptionEn: "A compressed view of rooftops and alleys documenting old-neighborhood density without over-polishing.",
      },
      {
        id: "he-golden-grid",
        type: "image",
        src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/89714a346_h_001.jpg",
        alt: "Golden aerial grid of old Saudi neighborhood streets and rooftops",
        title: "GOLDEN GRID",
        description: "شبكة المدينة من الأعلى؛ نهاية مثالية للقسم لأنها تكشف التراث كنظام حياة كامل.",
        descriptionEn: "The city grid from above — a closing frame revealing heritage as a complete living system.",
      }
    ],
  },
];