export const FEED_ITEMS = [
  {
    id: 1,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "تركي غازي",
    subtitle: "مصمم ومبدع بصري",
    category: null,
    isHero: true,
  },
  {
    id: 2,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "عوالم بصرية",
    subtitle: "تصنع بالذكاء الاصطناعي",
    category: "AI Visual",
  },
  {
    id: 3,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "GOLD ERA",
    subtitle: "حملة بصرية سينمائية",
    category: "AI Film",
  },
  {
    id: 4,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "PRODUCT PRO",
    subtitle: "تصميم منتج احترافي",
    category: "Product",
  },
  {
    id: 5,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "60 SEC CINEMATIC",
    subtitle: "إنتاج سينمائي مكثف",
    category: "Creative",
  },
  {
    id: 6,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "FASHION STUDIO",
    subtitle: "تصوير أزياء بالذكاء الاصطناعي",
    category: "AI Film",
  },
  {
    id: 7,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "DESERT VISION",
    subtitle: "رؤية إبداعية من الصحراء",
    category: "Heritage",
  },
  {
    id: 8,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "خلف الكواليس",
    subtitle: "العملية الإبداعية",
    category: "BTS",
  },
  {
    id: 9,
    type: "image",
    src: "/works/hero-poster.jpg",
    title: "الاستوديو",
    subtitle: "بيئة الإبداع",
    category: "BTS",
  },
  {
    id: 10,
    type: "brand",
    src: "/works/logo-coin.png",
    title: "TURKI STUDIO",
    subtitle: "نصنع عوالم بصرية بالذكاء الاصطناعي",
    category: null,
    isBrand: true,
  },
];