export const realEstateItems = [
  {
    id: "re-urban-luxury-tower",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/a88c46ce7_r_041.jpg",
    alt: "Luxury Riyadh residential building at night with skyline",
    title: "URBAN LUXURY",
    description: "واجهة سكنية فاخرة بإضاءة ليلية تجعل العقار يبدو كعنوان للرفاهية لا مجرد مبنى.",
    descriptionEn: "A luxury night façade positioning the property as a statement of refined urban living.",
  },
  {
    id: "re-najdi-modern",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/c4c94bda5_r_040.jpg",
    alt: "Modern Najdi inspired residential building with city skyline",
    title: "NAJDI MODERN",
    description: "مزج بين الزخرفة النجدية والعمارة الحديثة لصناعة مشروع يحمل هوية محلية عالية القيمة.",
    descriptionEn: "Najdi ornament meets modern architecture to create a locally rooted premium residence.",
  },
  {
    id: "re-golden-residence",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/577a075ec_r_039.jpg",
    alt: "Premium residential building glowing at golden hour",
    title: "GOLDEN RESIDENCE",
    description: "لقطة واجهة ذهبية تبرز دفء السكن، اتساع النوافذ، وحياة الداخل كعنصر بيع أساسي.",
    descriptionEn: "A golden façade frame highlighting warm interiors, wide glazing, and livable value.",
  },
  {
    id: "re-balcony-moment",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/752eeb990_r_038.jpg",
    alt: "Saudi couple on balcony overlooking sunset property view",
    title: "BALCONY MOMENT",
    description: "مشهد إنساني يبيع الإحساس قبل المساحة: عائلة، إطلالة، وقرار سكني مطمئن.",
    descriptionEn: "A human lifestyle moment selling feeling before square meters: view, family, and confidence.",
  },
  {
    id: "re-client-tour",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/b740817a8_r_037.jpg",
    alt: "Real estate consultants touring clients outside modern villa",
    title: "CLIENT TOUR",
    description: "تجربة المعاينة العقارية كقصة ثقة بين المستشار، العميل، والمكان.",
    descriptionEn: "A property viewing framed as a trust story between consultant, client, and place.",
  },
  {
    id: "re-advisor-portrait",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/c035375d1_r_036.jpg",
    alt: "Professional Saudi real estate advisor in front of premium building",
    title: "ADVISOR PRESENCE",
    description: "بورتريه مستشار عقاري يعطي العلامة وجهًا موثوقًا وحضورًا احترافيًا واضحًا.",
    descriptionEn: "A professional advisor portrait giving the brand a trusted, polished face.",
  },
  {
    id: "re-coffee-meeting",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/883835045_r_035.jpg",
    alt: "Real estate couple discussing investment with coffee in city street",
    title: "INVESTOR TALK",
    description: "لقطة حوارية مناسبة لحملات الاستثمار، تعكس القرار العقاري كجزء من نمط حياة عصري.",
    descriptionEn: "A conversational investment frame presenting real estate decisions as modern lifestyle moments.",
  },
  {
    id: "re-terrace-living",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/7cd1a89dc_r_034.jpg",
    alt: "Residential terrace apartments with warm interiors at sunset",
    title: "TERRACE LIVING",
    description: "إظهار الشرفات والخضرة والإضاءة الداخلية لصناعة رغبة سكنية هادئة وفاخرة.",
    descriptionEn: "Terraces, greenery, and interior glow create quiet premium residential desire.",
  },
  {
    id: "re-market-strategy",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/a93bc4529_r_033.jpg",
    alt: "Saudi real estate team planning market positioning strategy",
    title: "MARKET STRATEGY",
    description: "توظيف احترافي لخلفية التسويق العقاري: تحليل، تموضع، وتسعير قبل الإطلاق.",
    descriptionEn: "A professional real estate marketing frame: analysis, positioning, and launch planning.",
  },
  {
    id: "re-signature-deal",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/4e8fe0f25_r_032.jpg",
    alt: "Miniature Saudi property deal scene with contracts and materials",
    title: "SIGNATURE DEAL",
    description: "لقطة رمزية ذكية تربط العقد، الخامات، والثقة المالية في صورة واحدة سهلة التذكّر.",
    descriptionEn: "A symbolic frame connecting contract, materials, and financial trust in one memorable image.",
  },
  {
    id: "re-material-kit",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/5ad256a6d_r_031.jpg",
    alt: "Real estate material sample kit contracts coffee and Saudi hospitality",
    title: "MATERIAL KIT",
    description: "تفاصيل الخامات والضيافة والعقود تظهر المشروع كمنظومة متكاملة وليست صور مبنى فقط.",
    descriptionEn: "Materials, hospitality, and paperwork present the project as a complete premium system.",
  },
  {
    id: "re-desert-launch",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/bc60c49c5_r_030.jpg",
    alt: "Luxury desert real estate launch event with open door installation",
    title: "DESERT LAUNCH",
    description: "إطلاق عقاري بصري في الصحراء؛ باب مفتوح، دائرة ضوء، وحضور خاص يصنع تجربة علامة.",
    descriptionEn: "A desert launch experience with an open door, light circle, and premium brand presence.",
  },
  {
    id: "re-riyadh-door",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/b61770046_r_029.jpg",
    alt: "Saudi real estate deal in luxury interior with Riyadh skyline view",
    title: "RIYADH DOOR",
    description: "مجاز بصري قوي: باب تراثي يفتح على أفق الرياض، مثالي لحملات التحول والاستثمار.",
    descriptionEn: "A powerful metaphor: a heritage door opening to Riyadh skyline, ideal for investment campaigns.",
  },
  {
    id: "re-hologram-masterplan",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/2de8cc2f5_r_028.jpg",
    alt: "Saudi developer presenting holographic residential masterplan",
    title: "SMART MASTERPLAN",
    description: "عرض مشروع بتقنية مستقبلية يرفع قيمة العرض ويحوّل المخطط إلى تجربة تفاعلية.",
    descriptionEn: "A futuristic project presentation turning the masterplan into an interactive sales experience.",
  },
  {
    id: "re-table-model",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/bf0206403_r_027.jpg",
    alt: "Saudi investors reviewing holographic architectural model",
    title: "MODEL REVIEW",
    description: "جلسة بيع راقية حول نموذج معماري مضيء؛ التقنية تخدم الثقة وتسهّل القرار.",
    descriptionEn: "A premium sales meeting around a glowing model where technology builds confidence.",
  },
  {
    id: "re-boardroom-launch",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/4cc8c978a_r_026.jpg",
    alt: "Saudi real estate boardroom project launch with skyline and analytics",
    title: "BOARDROOM LAUNCH",
    description: "مشهد إطلاق للمستثمرين يجمع النموذج، التحليلات، وأفق الرياض كدليل على الجدية.",
    descriptionEn: "An investor launch frame combining model, analytics, and Riyadh skyline as proof of seriousness.",
  },
  {
    id: "re-brand-positioning",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/b3ef94f87_r_025.jpg",
    alt: "Real estate brand positioning workshop with Saudi team",
    title: "BRAND POSITIONING",
    description: "تسويق عقاري يبدأ من الحضور المختلف؛ لوحة، فريق، ورسائل واضحة قبل الإعلان.",
    descriptionEn: "Real estate marketing begins with distinct positioning: team, board, and clear messaging.",
  },
  {
    id: "re-development-journey",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/b1049e31a_r_024.jpg",
    alt: "Saudi real estate development journey from desert to skyline",
    title: "DEVELOPMENT JOURNEY",
    description: "صورة تلخص رحلة التطوير من الفكرة في الأرض إلى البناء ثم المدينة المكتملة.",
    descriptionEn: "A visual summary of development: land idea, construction progress, and completed city value.",
  },
  {
    id: "re-seed-concept",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/8df9f30df_r_023.jpg",
    alt: "Minimal real estate concept seed growing into modern building",
    title: "SEED CONCEPT",
    description: "مجاز بصري ناعم للمشروع العقاري كاستثمار يبدأ صغيرًا وينمو إلى أصل واضح القيمة.",
    descriptionEn: "A soft metaphor for property investment: a seed growing into a valuable built asset.",
  },
  {
    id: "re-launch-explainer",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/6f3553c89_r_022.jpg",
    alt: "Arabic real estate project launch explainer infographic",
    title: "LAUNCH EXPLAINER",
    description: "إنفوجرافيك تسويقي يشرح قيمة الإطلاق والتموضع بلغة بسيطة قابلة للنشر.",
    descriptionEn: "A marketing explainer that communicates launch value and positioning in a publishable format.",
  },
  {
    id: "re-mobile-tour",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/af5794a44_r_021.jpg",
    alt: "Mobile video property tour in front of apartment building",
    title: "MOBILE TOUR",
    description: "توظيف الهاتف كقناة بيع؛ العقار يظهر كمحتوى قابل للمشاهدة والمشاركة فورًا.",
    descriptionEn: "The phone as a sales channel — the property becomes instantly watchable and shareable.",
  },
  {
    id: "re-mamsha-residence",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/7648be73b_r_020.jpg",
    alt: "Al Mamsha residences urban mixed-use property exterior",
    title: "MAMSHA RESIDENCES",
    description: "واجهة حضرية قابلة للبيع بصريًا: مدخل واضح، حركة شارع، وخدمات بجانب السكن.",
    descriptionEn: "A sellable urban façade: clear entrance, street life, and services beside residences.",
  },
  {
    id: "re-corridor-luxury",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/3c341a93d_r_019.jpg",
    alt: "Luxury residential corridor with ornate open apartment door",
    title: "PRIVATE CORRIDOR",
    description: "الرفاهية تبدأ من الممر؛ باب مفتوح وإضاءة دافئة تبيع الخصوصية قبل الداخل.",
    descriptionEn: "Luxury starts in the corridor: an open door and warm lighting sell privacy before the room.",
  },
  {
    id: "re-architectural-model",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/db6530fd8_r_018.jpg",
    alt: "White architectural residential model under spotlight",
    title: "PHYSICAL MODEL",
    description: "نموذج معماري نظيف يعرض المشروع كمنتج ملموس ويزيد ثقة العميل قبل التنفيذ.",
    descriptionEn: "A clean architectural model making the project tangible and increasing buyer confidence.",
  },
  {
    id: "re-pool-villa",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/174ef80d8_r_017.jpg",
    alt: "Luxury villa pool at sunset with palm landscape",
    title: "POOL VILLA",
    description: "لقطة نمط حياة فاخرة تجمع المسبح، النخيل، والغروب لصناعة رغبة السكن الخاص.",
    descriptionEn: "A premium lifestyle shot combining pool, palms, and sunset to create private-living desire.",
  },
  {
    id: "re-sunset-villa",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/4e63c9300_r_016.jpg",
    alt: "Modern villa with pool and sunset reflection",
    title: "SUNSET VILLA",
    description: "فيلا حديثة بإضاءة غروب وانعكاس ماء؛ مثالية لإعلانات البيع العاطفي عالي القيمة.",
    descriptionEn: "A modern villa with sunset light and water reflection for high-value emotional property ads.",
  },
  {
    id: "re-open-door",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/4977d6d2d_r_015.jpg",
    alt: "Open wooden door into bright living room interior",
    title: "OPEN DOOR",
    description: "لقطة دخول ناعمة تبيع الإحساس بالبيت: مفتاح، خشب، ضوء، وراحة داخلية.",
    descriptionEn: "A soft entry frame selling the feeling of home: key, wood, light, and interior comfort.",
  },
  {
    id: "re-premium-interior",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/69c422d2f_r_014.jpg",
    alt: "Bright premium apartment interior seen through black door",
    title: "PREMIUM INTERIOR",
    description: "الداخل كدليل جودة؛ لون هادئ، أثاث متوازن، وباب أسود يعطي قيمة فاخرة.",
    descriptionEn: "Interior as proof of quality: calm tones, balanced furniture, and a black door with premium value.",
  },
  {
    id: "re-future-project",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/cf07af707_r_013.jpg",
    alt: "Arabic future project residential community at sunrise",
    title: "FUTURE PROJECT",
    description: "صورة إطلاق مباشرة تحمل وعدًا واضحًا: مشروع المستقبل الجديد بلغة بسيطة وقوية.",
    descriptionEn: "A direct launch image with a clear promise: the new future project in strong simple language.",
  },
  {
    id: "re-marble-detail",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/a6dce8a6b_r_012.jpg",
    alt: "Hand touching luxury marble wall in premium interior",
    title: "MARBLE TOUCH",
    description: "تفاصيل الخامة تبيع أكثر من اللقطة الواسعة؛ ملمس الرخام يصبح دليلًا على الفخامة.",
    descriptionEn: "Material detail sells beyond wide shots — marble touch becomes proof of luxury.",
  },
  {
    id: "re-riyadh-overlook",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/d0b06c257_r_010.jpg",
    alt: "Saudi man overlooking Riyadh skyline from rooftop",
    title: "RIYADH OVERLOOK",
    description: "صورة طموح عقاري؛ الوقوف فوق المدينة يربط المشروع بالمستقبل والمكانة.",
    descriptionEn: "A property ambition frame: overlooking the city links the project to future and status.",
  },
  {
    id: "re-live-broadcast",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/59efc5f8f_r_009.jpg",
    alt: "Luxury property live broadcast production studio",
    title: "LIVE PROPERTY",
    description: "تسويق عقاري كإنتاج إعلامي كامل: بث مباشر، شاشات، وفريق تصوير لرفع الثقة.",
    descriptionEn: "Real estate marketing as full media production: live broadcast, screens, and film crew.",
  },
  {
    id: "re-production-day",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/afda3fd60_r_008.jpg",
    alt: "Real estate video production set with drone and cinema camera outside villa",
    title: "PRODUCTION DAY",
    description: "ما وراء الكواليس يثبت الاحتراف: كاميرا سينما، درون، وفريق يرفع قيمة العرض العقاري.",
    descriptionEn: "Behind the scenes proves professionalism: cinema camera, drone, and crew elevating property value.",
  },
  {
    id: "re-heritage-residence",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/e94c20c45_r_007.jpg",
    alt: "Heritage inspired modern residence with Riyadh skyline",
    title: "HERITAGE RESIDENCE",
    description: "عمارة مستوحاة من التراث بلغة معاصرة؛ مشروع يبيع الهوية بقدر ما يبيع المساحة.",
    descriptionEn: "Heritage-inspired modern architecture selling identity as much as space.",
  },
  {
    id: "re-family-home",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/0c126fea0_r_006.jpg",
    alt: "Saudi family sitting together in bright home interior",
    title: "FAMILY HOME",
    description: "البيت كحياة: عائلة، دفء، وطمأنينة تجعل الرسالة العقارية إنسانية ومؤثرة.",
    descriptionEn: "Home as life: family, warmth, and reassurance make the property message human.",
  },
  {
    id: "re-modern-buyer",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/aadc1fabf_r_005.jpg",
    alt: "Modern Saudi buyer taking selfie near glass business towers",
    title: "MODERN BUYER",
    description: "المشتري الحديث حاضر رقميًا؛ صورة تربط العقار بالهوية الشخصية والمشاركة الاجتماعية.",
    descriptionEn: "The modern buyer is digitally present — property connects with personal identity and sharing.",
  },
  {
    id: "re-community-coffee",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/fcd39a756_r_004.jpg",
    alt: "Saudi couple having coffee in front of premium residential villa",
    title: "COMMUNITY COFFEE",
    description: "لقطة اجتماعية رقيقة تبيع الحي كعلاقات يومية وراحة خارج حدود الجدران.",
    descriptionEn: "A soft social frame selling the neighborhood as daily relationships beyond walls.",
  },
  {
    id: "re-palace-approach",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/8db36858b_r_003.jpg",
    alt: "Saudi man approaching luxury palace style property at golden hour",
    title: "PALACE APPROACH",
    description: "مدخل فاخر بزخارف محلية وضوء ذهبي؛ يضع العقار في مساحة الهيبة والخصوصية.",
    descriptionEn: "A luxury approach with local ornament and golden light placing the property in prestige.",
  },
  {
    id: "re-green-community",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/b6fde6fd7_r_002.jpg",
    alt: "Aerial green residential community in Riyadh with villas and gardens",
    title: "GREEN COMMUNITY",
    description: "مجتمع سكني أخضر من الأعلى؛ المسارات والحدائق والمسابح تبيع نمط حياة متكامل.",
    descriptionEn: "An aerial green community where paths, gardens, and pools sell a complete lifestyle.",
  },
  {
    id: "re-executive-lounge",
    type: "image",
    src: "https://media.base44.com/images/public/69f618d78f528f5ed96d2f9c/766796c0c_r_001.jpg",
    alt: "Luxury real estate executive lounge interior with Arabic art",
    title: "EXECUTIVE LOUNGE",
    description: "مساحة داخلية تنفيذية تصلح لبيع خدمات عقارية فاخرة، اجتماعات كبار العملاء، وهوية مكاتب راقية.",
    descriptionEn: "An executive interior for premium real estate services, VIP meetings, and refined office identity.",
  },
];