export const trainedCharacters = [
  {
    id: "noura-01",
    code: "CH·01",
    name: "نورا",
    nameEn: "Noura",
    role: "وجه سينمائي هادئ · حملات فاشن وجمال",
    tone: "شعر أسود طويل · ملامح متوازنة · حضور دافئ",
    bio: "نورا مناسبة للمشاهد الهادئة واللقطات الجمالية التي تحتاج حضورًا ناعمًا وثابتًا عبر أكثر من زاوية.",
    cover: "/works/trained_models/char_01/angle_1.jpg",
    accent: "#C9A961",
    images: [
      "/works/trained_models/char_01/angle_1.jpg",
      "/works/trained_models/char_01/angle_2.jpg",
      "/works/trained_models/char_01/angle_3.jpg",
      "/works/trained_models/char_01/angle_4.jpg",
      "/works/trained_models/char_01/angle_5.jpg",
      "/works/trained_models/char_01/angle_6.jpg",
      "/works/trained_models/char_01/angle_7.jpg",
      "/works/trained_models/char_01/angle_8.jpg",
      "/works/trained_models/char_01/angle_9.jpg",
      "/works/trained_models/char_01/angle_10.jpg",
    ],
  },
  {
    id: "rayan-02",
    code: "CH·02",
    name: "ريان",
    nameEn: "Rayan",
    role: "رجل عربي كلاسيكي · دراما وإعلانات راقية",
    tone: "شارب واضح · حضور واثق · ملامح سينمائية",
    bio: "ريان شخصية مناسبة للأدوار الدرامية، حملات العطور، واللقطات ذات الحضور الرجولي الكلاسيكي.",
    cover: "/works/trained_models/char_02/angle_1.jpg",
    accent: "#8B1E2D",
    images: [
      "/works/trained_models/char_02/angle_1.jpg",
      "/works/trained_models/char_02/angle_2.jpg",
      "/works/trained_models/char_02/angle_3.jpg",
      "/works/trained_models/char_02/angle_4.jpg",
      "/works/trained_models/char_02/angle_5.jpg",
      "/works/trained_models/char_02/angle_6.jpg",
      "/works/trained_models/char_02/angle_7.jpg",
      "/works/trained_models/char_02/angle_8.jpg",
      "/works/trained_models/char_02/angle_9.jpg",
      "/works/trained_models/char_02/angle_10.jpg",
    ],
  },
  {
    id: "layla-03",
    code: "CH·03",
    name: "ليلى",
    nameEn: "Layla",
    role: "شخصية متعددة الوجوه · فاشن وجمال وحضور سينمائي",
    tone: "ملامح ثابتة عبر أكثر من لوك، من الشعر المجعّد إلى الحضور القوي",
    bio: "ليلى ملف شخصية مستقل يجمع بين الحضور التحريري والجمالي، وتظهر بثبات بصري في لقطات قريبة، جانبية، ولقطات فاشن كاملة.",
    profileStory: "ليلى ليست مجرد وجه؛ هي شخصية قابلة لبناء حملة كاملة حولها، من كلوز أب الجمال إلى لوك الفاشن واللقطات السينمائية.",
    cover: "/works/trained_models/char_03/angle_1.jpg",
    accent: "#20364A",
    images: [
      "/works/trained_models/char_03/angle_1.jpg",
      "/works/trained_models/char_03/angle_2.jpg",
      "/works/trained_models/char_03/angle_3.jpg",
      "/works/trained_models/char_03/angle_4.jpg",
      "/works/trained_models/char_03/angle_5.jpg",
      "/works/trained_models/char_03/angle_6.jpg",
      "/works/trained_models/char_03/angle_1.jpg",
      "/works/trained_models/char_03/angle_2.jpg",
      "/works/trained_models/char_03/angle_3.jpg",
      "/works/trained_models/char_03/angle_4.jpg",
      "/works/trained_models/char_03/angle_5.jpg",
      "/works/trained_models/char_03/angle_6.jpg",
      "/works/trained_models/char_03/angle_7.jpg",
      "/works/trained_models/char_03/angle_8.jpg",
      "/works/trained_models/char_03/angle_9.jpg",
      "/works/trained_models/char_03/angle_10.jpg",
    ],
  },
  {
    id: "omar-04",
    code: "CH·04",
    name: "عمر",
    nameEn: "Omar",
    role: "شخصية إعلانية مرنة · UGC وفاشن ولايف ستايل",
    tone: "ابتسامة واضحة، حضور قريب، وتحوّل بصري بين أكثر من لوك",
    bio: "عمر ملف شخصية مستقل يخدم الإعلانات اليومية، المحتوى القريب من الجمهور، واللقطات التي تحتاج طاقة ودودة قابلة للتصديق.",
    profileStory: "عمر مصمم ليكون وجهًا إعلانيًا مرنًا؛ قريب من الجمهور، واضح في الأداء، وقادر على حمل قصة منتج أو حملة اجتماعية.",
    cover: "/works/trained_models/char_04/angle_1.jpg",
    accent: "#1E5A3E",
    images: [
      "/works/trained_models/char_04/angle_1.jpg",
      "/works/trained_models/char_04/angle_2.jpg",
      "/works/trained_models/char_04/angle_3.jpg",
      "/works/trained_models/char_04/angle_4.jpg",
      "/works/trained_models/char_04/angle_5.jpg",
      "/works/trained_models/char_04/angle_6.jpg",
      "/works/trained_models/char_04/angle_1.jpg",
      "/works/trained_models/char_04/angle_2.jpg",
      "/works/trained_models/char_04/angle_3.jpg",
      "/works/trained_models/char_04/angle_4.jpg",
      "/works/trained_models/char_04/angle_5.jpg",
      "/works/trained_models/char_04/angle_6.jpg",
      "/works/trained_models/char_04/angle_7.jpg",
      "/works/trained_models/char_04/angle_8.jpg",
      "/works/trained_models/char_04/angle_9.jpg",
      "/works/trained_models/char_04/angle_10.jpg",
    ],
  },
  {
    id: "jawad-07",
    code: "CH·07",
    name: "جواد",
    nameEn: "Jawad",
    role: "شخصية درامية قوية · أعمال سينمائية وتراثية",
    tone: "شارب كلاسيكي · ملامح حادة · حضور بطل",
    bio: "جواد مناسب للأفلام القصيرة، المشاهد التراثية، والبوسترات التي تحتاج بطلًا بصريًا واضح الملامح.",
    cover: "/works/trained_models/char_07/angle_1.jpg",
    accent: "#7B2130",
    images: [
      "/works/trained_models/char_07/angle_1.jpg",
      "/works/trained_models/char_07/angle_2.jpg",
      "/works/trained_models/char_07/angle_3.jpg",
      "/works/trained_models/char_07/angle_4.jpg",
      "/works/trained_models/char_07/angle_5.jpg",
      "/works/trained_models/char_07/angle_6.jpg",
      "/works/trained_models/char_07/angle_7.jpg",
      "/works/trained_models/char_07/angle_8.jpg",
      "/works/trained_models/char_07/angle_9.jpg",
      "/works/trained_models/char_07/angle_10.jpg",
    ],
  },
  {
    id: "sara-08",
    code: "CH·08",
    name: "سارة",
    nameEn: "Sara",
    role: "وجه عربي حديث · فاشن ولايف ستايل",
    tone: "شعر طويل · ملامح متوازنة · حضور تجاري راقٍ",
    bio: "سارة مناسبة للفاشن، اللايف ستايل، وحملات العلامات التي تبحث عن وجه عربي حديث وهادئ.",
    cover: "/works/trained_models/char_08/angle_1.jpg",
    accent: "#C9A961",
    images: [
      "/works/trained_models/char_08/angle_1.jpg",
      "/works/trained_models/char_08/angle_2.jpg",
      "/works/trained_models/char_08/angle_3.jpg",
      "/works/trained_models/char_08/angle_4.jpg",
      "/works/trained_models/char_08/angle_5.jpg",
      "/works/trained_models/char_08/angle_6.jpg",
    ],
  },
];